---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno-policies
    namespace: kyverno
  interval: 5m0s
  path: ./tenants/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
